import { getUser, getRepos } from "@/lib/github";
import AiSummaryCard from "@/components/AiSummaryCard";

// this page will be used to display the user's profile information and the summary of their repositories generated by AI.
export default async function ProfilePage({ params }) {
  // It takes in the username as a parameter and fetch the user's profile information and their repositories from the GitHub API.
  const { username } = await params;

  const [user, repos] = await Promise.all([
    getUser(username),
    getRepos(username),
  ]);
  return (
    <div>
      <h1>{user.name}</h1>
      <p>{user.bio}</p>
      {/* It passes the user and repository information to the AiSummaryCard component to display the summary in a card format. */}
      <AiSummaryCard user={user} repos={repos} />
    </div>
  );
}
