import { getUser, getRepos } from "../../../lib/github";
import AiSummaryCard from "../../../components/AiSummaryCard";
import ProfileHeader from "../../../components/ProfileHeader";
import RepoList from "../../../components/RepoList";
import LanguageChart from "../../../components/LanguageChart";
// this page will be used to display the user's profile information and the summary of their repositories generated by AI.
export default async function ProfilePage({ params }) {
  // It takes in the username as a parameter and fetch the user's profile information and their repositories from the GitHub API.
  const { username } = await params;

  const [user, repos] = await Promise.all([
    getUser(username),
    getRepos(username),
  ]);
  return (
    <div className="mx-auto max-w-3xl space-y-4 p-4">
      <ProfileHeader user={user} />
      {/* It passes the user and repository information to the AiSummaryCard component to display the summary in a card format. */}
      <AiSummaryCard username={username} repos={repos} />
      <LanguageChart repos={repos} />
      <RepoList repos={repos} />
    </div>
  );
}