"use client";

import {useState} from "react";

// this component will be used to display the summary of the user's repositories generated by AI. It will take in the username and the list of repositories as props and display the summary in a card format.

export default function AiSummaryCard({username, repos}) {
  const [summary, setSummary] = useState("");

  return (
    <div>
      
    </div>
  );
}