"use client";

import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";

// this component will be used to display the summary of the user's repositories generated by AI. It will take in the username and the list of repositories as props and display the summary in a card format.

export default function AiSummaryCard({ username, repos }) {
  // useChat is a hook that provides the messages, sendMessage function, status of the chat (streaming or not), and a stop function to halt the streaming. It manages the state of the chat and allows for sending messages to the AI and receiving responses.

  // error becomes truthy if a request fails; regenerate() retries just the last message, not the whole conversation.
  const {
    messages,
    sendMessage,
    status,
    stop,
    setMessages,
    error,
    regenerate,
  } = useChat({
    transport: new DefaultChatTransport({ api: "/api/analyze" }),
  });
  function handleAnalyze() {
    setMessages([]); // clear previous conversation before sending a new one

    const trimmedRepos = repos
      .sort((a, b) => b.stargazers_count - a.stargazers_count)
      .slice(0, 5)
      .map((repo) => ({
        name: repo.name,
        language: repo.language,
        stars: repo.stargazers_count,
        forks: repo.forks_count,
        updated_at: repo.updated_at,
        description: repo.description,
      }));
    sendMessage({
      text: `Analyze this GitHub user: ${username}. Repositories: ${JSON.stringify(trimmedRepos)}`,
    });
  }

  // "submitted" covers the brief moment after clicking but before streaming actually starts, so the UI doesn't flicker.
  const loading = status === "streaming" || status === "submitted";
  const latestMessage = messages.filter((m) => m.role === "assistant").pop();

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-4 max-w-full">
      <div className="flex gap-2 mb-3">
        <button
          onClick={handleAnalyze}
          disabled={loading}
          className="px-3 py-1.5 rounded bg-violet-600 text-white text-sm disabled:opacity-50"
        >
          {loading ? "Analyzing..." : "Analyze Profile"}
        </button>
        {loading && (
          <button
            onClick={stop}
            className="px-3 py-1.5 rounded border border-zinc-700 text-zinc-300 text-sm"
          >
            Stop
          </button>
        )}
      </div>

      {/* designed error state with a working retry button. regenerate() only retries
          the failed message, not the whole conversation from scratch. */}
      {error && (
        <div className="mb-3 flex items-center justify-between gap-3 rounded-md border border-red-900 bg-red-950/40 px-3 py-2 text-sm text-red-300">
          <span>Something went wrong generating this summary.</span>
          <button
            onClick={() => regenerate()}
            className="shrink-0 rounded border border-red-800 px-2 py-1 text-xs text-red-200 hover:bg-red-900/40"
          >
            Retry
          </button>
        </div>
      )}

      {loading && !latestMessage && !error && (
        <div className="animate-pulse space-y-3">
          <div className="rounded-md border border-zinc-800 bg-zinc-950 p-4">
            <div className="h-8 w-16 rounded bg-zinc-800 mb-2" />
            <div className="h-3 w-48 rounded bg-zinc-800" />
          </div>
          <div className="h-3 w-full rounded bg-zinc-800" />
          <div className="h-3 w-5/6 rounded bg-zinc-800" />
          <div className="h-3 w-4/6 rounded bg-zinc-800" />
        </div>
      )}

      {/* first-run empty state — nothing analyzed yet, no error, not loading.
          gives the user a clear next action instead of a blank card. */}
      {!loading && !latestMessage && !error && (
        <p className="text-zinc-500 text-sm">
          Click "Analyze Profile" to get an AI-generated summary of this
          developer's strengths and activity.
        </p>
      )}

      {/* each message can have multiple "parts" — plain text chunks, or tool-call events.
          it loops through them and render each differently based on its type. */}
      {latestMessage?.parts.map((part, i) => {
        if (part.type === "text") {
          return (
            <p
              key={i}
              className="text-zinc-100 text-sm whitespace-pre-wrap mb-3"
            >
              {part.text}
            </p>
          );
        }
        // this is the part of the message that contains the output from the scoreProfile tool.
        if (part.type === "tool-scoreProfile") {
          if (part.state === "input-streaming") {
            // part.state is to show the current state of the tool call. It can be "input-streaming", "input-available", "output-available", or "output-error". Each state is rendered differently to provide feedback to the user about the progress of the analysis.
            return (
              <div
                key={i}
                className="mb-3 flex items-center gap-2 rounded-md border border-zinc-800 bg-zinc-950 px-3 py-2 text-xs text-zinc-500"
              >
                <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-zinc-500" />
                Deciding which repos to score…
              </div>
            );
          }

          if (part.state === "input-available") {
            // input-available state indicates that the input data for the scoreProfile tool is ready, and the AI is now calculating the score based on the provided repository data.
            return (
              <div
                key={i}
                className="mb-3 flex items-center gap-2 rounded-md border border-violet-900 bg-violet-950/40 px-3 py-2 text-xs text-violet-300"
              >
                <span className="h-1.5 w-1.5 animate-spin rounded-full border border-violet-300 border-t-transparent" />
                Calculating activity score from {part.input?.repos?.length ?? 0}{" "}
                repos…
              </div>
            );
          }

          if (part.state === "output-available") {
            // just like the input-available state, the output-available state indicates that the scoreProfile tool has finished processing the input data and has produced a score and reasoning. This is where the final results are displayed to the user.
            const { score, reasoning } = part.output;
            return (
              <div
                key={i}
                className="mb-3 rounded-md border border-zinc-800 bg-zinc-950 p-4"
              >
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-mono font-bold text-violet-400">
                    {score}
                  </span>
                  <span className="text-xs text-zinc-500">
                    / 100 activity score
                  </span>
                </div>
                <p className="mt-2 text-sm text-zinc-400">{reasoning}</p>
              </div>
            );
          }

          if (part.state === "output-error") {
            // output-error state indicates that there was an error while calculating the score for the GitHub developer's profile. The error message is displayed to inform the user that the score could not be calculated.
            return (
              <div
                key={i}
                className="mb-3 rounded-md border border-red-900 bg-red-950/40 px-3 py-2 text-xs text-red-300"
              >
                Couldn't calculate a score for this profile. {part.errorText}
              </div>
            );
          }
        }

        return null;
      })}
    </div>
  );
}
