"use client";

import { useState, useRef } from "react";

// this component will be used to display the summary of the user's repositories generated by AI. It will take in the username and the list of repositories as props and display the summary in a card format.

export default function AiSummaryCard({ username, repos }) {
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(false);
  const controllerRef = useRef(null);

  async function handleAnalyze() {
    // Implementation for analyzing repositories. This would typically involve calling the AI analysis endpoint
    setSummary("Analyzing...");
    setLoading(true);
    controllerRef.current = new AbortController();// a built-in browser tool that can cancel an in-progress fetch request. This is useful for stopping the analysis if the user decides to cancel it before it completes.
    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username, repos }),
        signal: controllerRef.current.signal,
      });
      // getReader() lets you pull pieces of the response body as they arrive, rather than waiting for the entire response to be received.
      const reader = response.body.getReader();

      //TextDecoder the stream sends raw bytes, not readable text directly; the decoder converts those bytes into actual text you can display.
      const decoder = new TextDecoder();
      let result = "";

      while (true) {
        // asks the reader for the next chunk.The done property is a boolean that indicates whether the stream has been fully read, and the value property contains the next chunk of data from the stream.
        const { done, value } = await reader.read();
        if (done) break;

        result += decoder.decode(value);
        setSummary(result);
      }
    } catch (error) {
      if (error.name === "AbortError") {
        setSummary("Something went wrong. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  }

  function handleStop() {
    controllerRef.current?.abort();
    setLoading(false);
  }
  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-4 max-w-full">
      <div className="flex gap-2 mb-3">
        <button
          onClick={handleAnalyze}
          disabled={loading}
          className="px-3 py-1.5 rounded bg-violet-500 text-white text-sm disabled:opacity-50"
        >
          {loading ? "Analyzing..." : "Analyze Profile"}
        </button>
        {loading && (
          <button
            onClick={handleStop}
            className="px-3 py-1.5 rounded border border-zinc-700 text-zinc-300 text-sm"
          >
            Stop
          </button>
        )}
      </div>
      {loading && summary === "" && (
        <p className="text-zinc-400 text-sm">Thinking…</p>
      )}
      <p className="text-zinc-100 text-sm whitespace-pre-wrap">{summary}</p>
    </div>
  );
}
